version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: gremlindesk-janusgraph
    ports:
      - "8182:8182"
    # Note: If docker pulls fail due to arm64, uncomment the platform line
    # platform: linux/amd64
